#!/usr/bin/env sh

# N.B. do not change this flag as this could expose secrets in log files
set +x

SECRET_ID=$1
APP=$2

TMP_FILE=`mktemp`
trap "{ rm -f $TMP_FILE; }" EXIT

aws secretsmanager get-secret-value --secret-id $SECRET_ID | jq -r '.SecretString' | json_to_exports > $TMP_FILE

source $TMP_FILE
echo echo Secrets loaded for "$SECRET_ID"
