#!/usr/bin/env sh

# N.B. do not change this flag as this could expose secrets in log files
set +x

SECRET_ID=$1
APP=$2

SECRETS_JSON=`aws secretsmanager get-secret-value --secret-id $SECRET_ID | jq -r '.SecretString'`

`echo $SECRETS_JSON | json_to_exports $APP`
echo echo Secrets loaded for "$SECRET_ID"
